return {
  'folke/which-key.nvim',
  event = 'VeryLazy',
  config = function()
    local wk = require('which-key')
    wk.setup({
      plugins = {
        spelling = { enabled = true },
      },
    })

    -- Register leader key groups
    wk.add({
      { "<leader>b", desc = "Buffers" },
      { "<leader>c", group = "Code" },
      { "<leader>ca", desc = "Code Action" },
      { "<leader>d", group = "DAP/Diagnostics" },
      { "<leader>dr", desc = "DAP REPL" },
      { "<leader>dl", desc = "DAP Run Last" },
      { "<leader>f", group = "Find" },
      { "<leader>fa", desc = "Find All (grep)" },
      { "<leader>fd", desc = "Find in Directory" },
      { "<leader>ff", desc = "Find Files" },
      { "<leader>fl", desc = "File Browser" },
      { "<leader>fo", group = "Obsidian Find" },
      { "<leader>fof", desc = "Find Obsidian Files" },
      { "<leader>fot", desc = "Find Obsidian Tags" },
      { "<leader>ft", desc = "Find TODOs" },
      { "<leader>fw", desc = "Format/Write" },
      { "<leader>g", group = "Git" },
      { "<leader>gb", desc = "Git Blame" },
      { "<leader>gc", desc = "Git Commit" },
      { "<leader>gd", desc = "Git Diff" },
      { "<leader>gg", desc = "Git Status" },
      { "<leader>gl", desc = "Git Log" },
      { "<leader>gp", desc = "Git Push" },
      { "<leader>gP", desc = "Git Pull" },
      { "<leader>gs", desc = "Git Status (Telescope)" },
      { "<leader>h", group = "Hunk (Git)" },
      { "<leader>hb", desc = "Blame Line" },
      { "<leader>hd", desc = "Diff This" },
      { "<leader>hD", desc = "Diff This ~" },
      { "<leader>hp", desc = "Preview Hunk" },
      { "<leader>hr", desc = "Reset Hunk" },
      { "<leader>hR", desc = "Reset Buffer" },
      { "<leader>hs", desc = "Stage Hunk" },
      { "<leader>hS", desc = "Stage Buffer" },
      { "<leader>hu", desc = "Undo Stage Hunk" },
      { "<leader>i", group = "LSP" },
      { "<leader>ih", desc = "Toggle Inlay Hints" },
      { "<leader>o", group = "Obsidian" },
      { "<leader>on", desc = "New Note" },
      { "<leader>ot", desc = "Today" },
      { "<leader>ow", desc = "Workspace" },
      { "<leader>p", group = "Plugin Manager" },
      { "<leader>pi", desc = "Install Plugins" },
      { "<leader>pu", desc = "Update Plugins" },
      { "<leader>r", group = "Rename" },
      { "<leader>rn", desc = "Rename Symbol" },
      { "<leader>t", group = "Toggle/Tab/Test" },
      { "<leader>tb", desc = "Toggle Breakpoint/Blame" },
      { "<leader>tc", desc = "Close Tab" },
      { "<leader>td", desc = "Toggle Deleted" },
      { "<leader>tn", desc = "New Tab" },
      { "<leader>tw", desc = "Trim Whitespace" },
      { "<leader>w", group = "Worktree" },
      { "<leader>wc", desc = "Create Worktree" },
      { "<leader>wl", desc = "List Worktrees" },
      { "g", group = "Go to" },
      { "gd", desc = "Definition" },
      { "gD", desc = "Type Definition" },
      { "gi", desc = "Implementation" },
      { "gr", desc = "References" },
      { "[", group = "Previous" },
      { "[b", desc = "Previous Buffer" },
      { "[h", desc = "Previous Hunk" },
      { "]", group = "Next" },
      { "]b", desc = "Next Buffer" },
      { "]h", desc = "Next Hunk" },
    })
  end,
}
